import random
import string
from datetime import datetime

from django.utils import timezone

search_results = [
    {
        "company": "Mega Appliance Repair",
        "serviceType": "Appliance repair and maintenance",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦950 - ₦1800 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "Are you a User Experience Designer with a track record of delivering intuitive digital experiences that drive results?...",
        "reviews": [
            {
                "reviewer": "Ariel Houessou",
                "avatar": "img/user/avatar/img-5.jpg",
                "date": "August 13, 2023",
                "rating": 4.8,
                "comment": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                "email": "daniel.young@example.com",
            },
        ],
    },
    {
        "company": "Secure Locksmiths",
        "serviceType": "Locksmith services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦1200 - ₦2200 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "Secure Locksmiths is a trusted provider of locksmith services, offering prompt and reliable solutions for residential and commercial properties. We prioritize the security and satisfaction of our clients.",
        "reviews": [
            {
                "reviewer": "Sophia Müller",
                "avatar": "img/user/avatar/img-14.jpg",
                "date": "May 27, 2023",
                "rating": 4.6,
                "comment": "Secure Locksmiths came to my rescue when I got locked out of my apartment. The locksmith arrived quickly, was professional and skilled, and gained access to my property without causing any damage.",
                "email": "sophia.young@example.com",
            },
        ],
    },
    {
        "company": "Eco-Cleaners",
        "serviceType": "House cleaning services",
        "location": "Abuja, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦800 - ₦1500 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "Eco-Cleaners is committed to providing top-notch house cleaning services using eco-friendly products. We strive to create a clean and healthy environment for our clients.",
        "reviews": [
            {
                "reviewer": "John Okoye",
                "avatar": "img/user/avatar/img-3.jpg",
                "date": "June 2, 2023",
                "rating": 4.9,
                "comment": "I'm extremely satisfied with the house cleaning service provided by Eco-Cleaners. The team was punctual, thorough, and left my home spotless. Highly recommended!",
                "email": "emily.campbell@example.com",
            },
            {
                "reviewer": "Grace Adekunle",
                "avatar": "img/user/avatar/img-9.jpg",
                "date": "May 29, 2023",
                "rating": 4.7,
                "comment": "Eco-Cleaners did an excellent job cleaning my house. The cleaners were polite, professional, and paid attention to every detail. I will definitely hire them again.",
                "email": "emily.campbell@example.com",
            },
        ],
    },
    {
        "company": "Garden Guru",
        "serviceType": "Gardening and landscaping services",
        "location": "Ibadan, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦1000 - ₦2000 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "Garden Guru specializes in transforming outdoor spaces into beautiful and vibrant gardens. Our team of skilled gardeners and landscapers is passionate about creating personalized and stunning landscapes.",
        "reviews": [
            {
                "reviewer": "Samuel Adekoya",
                "avatar": "img/user/avatar/img-8.jpg",
                "date": "June 1, 2023",
                "rating": 4.8,
                "comment": "The team from Garden Guru did an exceptional job in designing and maintaining my garden. They are knowledgeable, creative, and dedicated to their work. My garden has become a peaceful oasis!",
                "email": "emily.campbell@example.com",
            },
            {
                "reviewer": "Bisi Adeyemi",
                "avatar": "img/user/avatar/img-15.jpg",
                "date": "May 30, 2023",
                "rating": 4.6,
                "comment": "I'm thrilled with the landscaping services provided by Garden Guru. They transformed my backyard into a stunning space with beautiful plants and hardscape features. Highly recommended!",
                "email": "emily.campbell@example.com",
            },
        ],
    },
    {
        "company": "QuickFix Electricians",
        "serviceType": "Electrical repair and installation",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦1200 - ₦2500 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "QuickFix Electricians is a team of skilled and certified electricians providing reliable electrical repair and installation services. We prioritize safety, efficiency, and customer satisfaction.",
        "reviews": [
            {
                "reviewer": "Oluwaseun Bakare",
                "avatar": "img/user/avatar/img-12.jpg",
                "date": "May 31, 2023",
                "rating": 4.7,
                "comment": "I had a great experience with QuickFix Electricians. They responded promptly to my electrical issue, diagnosed and fixed it quickly. The electrician was knowledgeable and professional throughout the process.",
                "email": "emily.campbell@example.com",
            },
            {
                "reviewer": "Chinedu Okafor",
                "avatar": "img/user/avatar/img-10.jpg",
                "date": "May 28, 2023",
                "rating": 4.5,
                "comment": "QuickFix Electricians did an excellent job installing new electrical fixtures in my home. The electricians were skilled, courteous, and completed the work to my satisfaction. I would hire them again.",
                "email": "emily.campbell@example.com",
            },
        ],
    },
    {
        "company": "PlumbMaster",
        "serviceType": "Plumbing services",
        "location": "Port Harcourt, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦1000 - ₦1800 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "PlumbMaster is a trusted provider of plumbing services, catering to residential and commercial clients. Our team of experienced plumbers delivers reliable and efficient plumbing solutions.",
        "reviews": [
            {
                "reviewer": "Nneka Eze",
                "avatar": "img/user/avatar/img-2.jpg",
                "date": "May 30, 2023",
                "rating": 4.9,
                "comment": "I highly recommend PlumbMaster for any plumbing needs. They fixed a leaking pipe in my house, and the plumber was professional, friendly, and skilled. The issue was resolved quickly and efficiently.",
                "email": "emily.campbell@example.com",
            },
            {
                "reviewer": "James Obi",
                "avatar": "img/user/avatar/img-7.jpg",
                "date": "May 27, 2023",
                "rating": 4.7,
                "comment": "PlumbMaster provided exceptional plumbing services in my office building. The plumbers were prompt, knowledgeable, and resolved the issues with the plumbing system effectively. I'm satisfied with their work.",
                "email": "emily.campbell@example.com",
            },
        ],
    },
    {
        "company": "FreshAir HVAC Services",
        "serviceType": "Heating, ventilation, and air conditioning services",
        "location": "Kano, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦1500 - ₦2800 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "FreshAir HVAC Services offers comprehensive HVAC services, including installation, repair, and maintenance. Our experienced technicians ensure optimal comfort and air quality for our clients.",
        "reviews": [
            {
                "reviewer": "Hassan Ibrahim",
                "avatar": "img/user/avatar/img-4.jpg",
                "date": "May 29, 2023",
                "rating": 4.6,
                "comment": "FreshAir HVAC Services did an excellent job installing a new air conditioning unit in my home. The technicians were skilled, efficient, and explained everything clearly. I'm pleased with their service.",
                "email": "emily.campbell@example.com",
            },
            {
                "reviewer": "Aisha Bello",
                "avatar": "img/user/avatar/img-13.jpg",
                "date": "May 26, 2023",
                "rating": 4.8,
                "comment": "I had a great experience with FreshAir HVAC Services. They promptly repaired my malfunctioning heating system and restored its functionality. The technicians were professional and friendly.",
                "email": "emily.campbell@example.com",
            },
        ],
    },
    {
        "company": "Secure Locksmiths",
        "serviceType": "Locksmith services",
        "location": "Kaduna, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦900 - ₦1600 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "Secure Locksmiths is a reliable locksmith service provider, offering a range of services, including lock installation, key duplication, and emergency lockout assistance. We prioritize customer satisfaction and security.",
        "reviews": [
            {
                "reviewer": "Abdullahi Musa",
                "avatar": "img/user/avatar/img-14.jpg",
                "date": "May 28, 2023",
                "rating": 4.7,
                "comment": "Secure Locksmiths provided quick and efficient lock installation services for my apartment. The locksmith was skilled, professional, and ensured that the locks were of high quality. I'm impressed with their service.",
                "email": "emily.campbell@example.com",
            },
            {
                "reviewer": "Fatima Mohammed",
                "avatar": "img/user/avatar/img-6.jpg",
                "date": "May 25, 2023",
                "rating": 4.5,
                "comment": "I had a positive experience with Secure Locksmiths when I needed emergency lockout assistance. The locksmith arrived promptly, resolved the issue quickly, and showed excellent customer service.",
                "email": "emily.campbell@example.com",
            },
        ],
    },
    {
        "company": "PaintPro",
        "serviceType": "Painting services",
        "location": "Enugu, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦1200 - ₦2000 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "PaintPro is a team of skilled painters providing high-quality painting services for residential and commercial properties. We use premium materials and techniques to deliver exceptional results.",
        "reviews": [
            {
                "reviewer": "Chinwe Okonkwo",
                "avatar": "img/user/avatar/img-11.jpg",
                "date": "May 27, 2023",
                "rating": 4.9,
                "comment": "PaintPro did a fantastic job painting my house. The painters were meticulous, detailed, and completed the project on time. The quality of their work exceeded my expectations.",
                "email": "emily.campbell@example.com",
            },
            {
                "reviewer": "Emeka Okafor",
                "avatar": "img/user/avatar/img-16.jpg",
                "date": "May 24, 2023",
                "rating": 4.7,
                "comment": "I'm pleased with the painting services provided by PaintPro. The painters were professional, friendly, and paid attention to every detail. They transformed my office space beautifully.",
                "email": "emily.campbell@example.com",
            },
        ],
    },
    {
        "company": "Roofing Experts",
        "serviceType": "Roof repair and installation",
        "location": "Benin City, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦1500 - ₦2500 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "Roofing Experts specializes in roof repair, installation, and maintenance services. Our team of experienced roofers ensures durable and weather-resistant roofs for homes and commercial buildings.",
        "reviews": [
            {
                "reviewer": "Daniel Osagie",
                "avatar": "img/user/avatar/img-17.jpg",
                "date": "May 26, 2023",
                "rating": 4.8,
                "comment": "I highly recommend Roofing Experts for any roofing needs. They repaired a leaking roof in my house, and the roofers were professional, efficient, and used high-quality materials. Great service!",
                "email": "emily.campbell@example.com",
            },
            {
                "reviewer": "Joy Eze",
                "avatar": "img/user/avatar/img-18.jpg",
                "date": "May 23, 2023",
                "rating": 4.6,
                "comment": "Roofing Experts did an excellent job installing a new roof on my commercial building. The roofers were skilled, reliable, and completed the project within the specified time. I'm satisfied with their work.",
                "email": "emily.campbell@example.com",
            },
        ],
    },
    {
        "company": "Furniture Fixers",
        "serviceType": "Furniture repair and restoration",
        "location": "Katsina, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦1000 - ₦1800 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "Furniture Fixers specializes in repairing and restoring furniture to its former glory. Our skilled craftsmen have expertise in handling all types of furniture, ensuring exceptional results.",
        "reviews": [
            {
                "reviewer": "Oluwakemi Adesina",
                "avatar": "img/user/avatar/img-19.jpg",
                "date": "May 25, 2023",
                "rating": 4.9,
                "comment": "I'm delighted with the furniture repair services provided by Furniture Fixers. They restored my antique table beautifully, paying attention to every detail. The craftsmen were professional and knowledgeable.",
                "email": "emily.campbell@example.com",
            },
            {
                "reviewer": "Abdul Rahman",
                "avatar": "img/user/avatar/img-20.jpg",
                "date": "May 22, 2023",
                "rating": 4.7,
                "comment": "Furniture Fixers did an amazing job repairing my damaged sofa. The craftsmen were skilled, efficient, and restored the sofa to its original condition. I'm impressed with their workmanship.",
                "email": "emily.campbell@example.com",
            },
        ],
    },
    {
        "company": "ElectroCool",
        "serviceType": "Air Conditioning Services",
        "location": "Abuja, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦1200 - ₦2000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "ElectroCool specializes in providing top-notch air conditioning services for residential and commercial properties. Our skilled technicians ensure efficient installation, repair, and maintenance of air conditioning systems.",
        "reviews": [
            {
                "reviewer": "Sarah Johnson",
                "avatar": "img/user/avatar/img-21.jpg",
                "date": "June 1, 2023",
                "rating": 4.8,
                "comment": "I had a great experience with ElectroCool. They installed an air conditioner in my home, and it works perfectly. The technicians were professional and friendly. Highly recommended!",
                "email": "sarah.johnson@example.com",
            },
            {
                "reviewer": "Michael Obi",
                "avatar": "img/user/avatar/img-22.jpg",
                "date": "May 29, 2023",
                "rating": 4.6,
                "comment": "I contacted ElectroCool for air conditioning repair, and they did an excellent job. The technicians arrived on time, diagnosed the issue quickly, and fixed it efficiently. Satisfied with their service.",
                "email": "michael.obi@example.com",
            },
        ],
    },
    {
        "company": "Garden Paradise",
        "serviceType": "Gardening and Landscaping",
        "location": "Port Harcourt, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦1000 - ₦1800 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "Garden Paradise is dedicated to creating beautiful and sustainable gardens and landscapes. Our team of expert gardeners provides comprehensive gardening and landscaping services to enhance outdoor spaces.",
        "reviews": [
            {
                "reviewer": "Emily Williams",
                "avatar": "img/user/avatar/img-23.jpg",
                "date": "June 2, 2023",
                "rating": 4.9,
                "comment": "Garden Paradise transformed my backyard into a stunning garden. The gardeners were knowledgeable, creative, and attentive to my preferences. They exceeded my expectations. Highly recommended!",
                "email": "emily.williams@example.com",
            },
            {
                "reviewer": "David Adeyemi",
                "avatar": "img/user/avatar/img-24.jpg",
                "date": "May 30, 2023",
                "rating": 4.7,
                "comment": "I'm impressed with the gardening services provided by Garden Paradise. They maintain my garden regularly and ensure it looks vibrant and healthy. The gardeners are professional and reliable.",
                "email": "david.adeyemi@example.com",
            },
        ],
    },
    {
        "company": "PlumbPros",
        "serviceType": "Plumbing Services",
        "location": "Ibadan, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦900 - ₦1600 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "PlumbPros offers a wide range of plumbing services for residential and commercial properties. Our skilled plumbers are equipped to handle all plumbing needs, from repairs and installations to maintenance and inspections.",
        "reviews": [
            {
                "reviewer": "Jennifer Smith",
                "avatar": "img/user/avatar/img-25.jpg",
                "date": "June 3, 2023",
                "rating": 4.8,
                "comment": "PlumbPros provided excellent plumbing services for my home. They fixed a leaking pipe and installed new fixtures. The plumbers were professional, efficient, and delivered high-quality work.",
                "email": "jennifer.smith@example.com",
            },
        ],
    },
    {
        "company": "PaintPro",
        "serviceType": "Painting Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦500 - ₦250,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "PaintPro is a professional painting company that provides high-quality painting services for residential and commercial properties. Our skilled painters deliver exceptional results with attention to detail.",
        "reviews": [
            {
                "reviewer": "John Doe",
                "avatar": "img/user/avatar/img-31.jpg",
                "date": "June 5, 2023",
                "rating": 4.3,
                "comment": "PaintPro did a good job painting my house. The painters were skilled and completed the project on time. I'm satisfied with their service.",
                "email": "john.doe@example.com",
            },
            {
                "reviewer": "Jane Smith",
                "avatar": "img/user/avatar/img-32.jpg",
                "date": "June 3, 2023",
                "rating": 3.8,
                "comment": "I hired PaintPro for a commercial painting project. While the end result was decent, there were some minor issues with the paint finish. Overall, an average experience.",
                "email": "jane.smith@example.com",
            },
        ],
    },
    {
        "company": "CleanSweep",
        "serviceType": "House Cleaning Services",
        "location": "Abuja, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦300 - ₦500,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "CleanSweep offers comprehensive house cleaning services to ensure a clean and hygienic living space. Our professional cleaners pay attention to detail and deliver exceptional cleaning results.",
        "reviews": [
            {
                "reviewer": "Michael Johnson",
                "avatar": "img/user/avatar/img-33.jpg",
                "date": "June 6, 2023",
                "rating": 4.5,
                "comment": "CleanSweep provides excellent house cleaning services. The cleaners are thorough, efficient, and polite. I'm happy with the quality of their work.",
                "email": "michael.johnson@example.com",
            },
            {
                "reviewer": "Emily Brown",
                "avatar": "img/user/avatar/img-34.jpg",
                "date": "June 4, 2023",
                "rating": 4.2,
                "comment": "I had a satisfactory experience with CleanSweep. The cleaners arrived on time and completed the cleaning tasks as requested. However, there were a few missed spots that could have been better.",
                "email": "emily.brown@example.com",
            },
        ],
    },
    {
        "company": "FixItAll",
        "serviceType": "Handyman Services",
        "location": "Port Harcourt, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦200 - ₦750,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "FixItAll is your one-stop solution for all handyman services. From electrical repairs and plumbing work to carpentry and home maintenance, our skilled handymen provide reliable and efficient services.",
        "reviews": [
            {
                "reviewer": "Jessica Davis",
                "avatar": "img/user/avatar/img-35.jpg",
                "date": "June 7, 2023",
                "rating": 4.7,
                "comment": "FixItAll is my go-to handyman service. The handymen are skilled, reliable, and handle various repair tasks with ease. Highly recommended!",
                "email": "jessica.davis@example.com",
            },
            {
                "reviewer": "Andrew Wilson",
                "avatar": "img/user/avatar/img-36.jpg",
                "date": "June 5, 2023",
                "rating": 4.9,
                "comment": "I've used FixItAll for multiple home repairs, and they never disappoint. The handymen are knowledgeable, prompt, and provide excellent service. I'm extremely satisfied!",
                "email": "andrew.wilson@example.com",
            },
        ],
    },
    {
        "company": "SparkleWash",
        "serviceType": "Pressure Washing Services",
        "location": "Ibadan, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦150 - ₦500,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "SparkleWash specializes in providing professional pressure washing services for residential and commercial properties. Our state-of-the-art equipment ensures effective cleaning of various surfaces.",
        "reviews": [
            {
                "reviewer": "Oliver Jackson",
                "avatar": "img/user/avatar/img-37.jpg",
                "date": "June 8, 2023",
                "rating": 4.6,
                "comment": "SparkleWash did a fantastic job pressure washing my driveway. The results were impressive, and the service was prompt and reliable. I'm highly satisfied!",
                "email": "oliver.jackson@example.com",
            },
            {
                "reviewer": "Sophia Thompson",
                "avatar": "img/user/avatar/img-38.jpg",
                "date": "June 6, 2023",
                "rating": 4.2,
                "comment": "I hired SparkleWash for pressure washing my patio. While the overall service was good, there were a few missed spots that could have been better. Still, a decent experience.",
                "email": "sophia.thompson@example.com",
            },
        ],
    },
    {
        "company": "TechSupport",
        "serviceType": "IT Support Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦100 - ₦200,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "TechSupport provides reliable and efficient IT support services for individuals and businesses. Our team of skilled technicians resolves computer issues, sets up networks, and ensures smooth IT operations.",
        "reviews": [
            {
                "reviewer": "William Davis",
                "avatar": "img/user/avatar/img-39.jpg",
                "date": "June 9, 2023",
                "rating": 4.8,
                "comment": "TechSupport has been instrumental in keeping our company's IT infrastructure running smoothly. Their technicians are knowledgeable, responsive, and deliver excellent support.",
                "email": "william.davis@example.com",
            },
            {
                "reviewer": "Sophie Wilson",
                "avatar": "img/user/avatar/img-40.jpg",
                "date": "June 7, 2023",
                "rating": 4.5,
                "comment": "I contacted TechSupport for computer repair, and they resolved the issue quickly. The technicians were friendly and provided helpful advice. Satisfied with their service.",
                "email": "sophie.wilson@example.com",
            },
        ],
    },
    {
        "company": "RoofMaster",
        "serviceType": "Roofing Services",
        "location": "Abuja, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦250 - ₦800,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "RoofMaster is a leading provider of roofing services. Our experienced roofers deliver top-quality installations, repairs, and maintenance to ensure durable and leak-free roofs.",
        "reviews": [
            {
                "reviewer": "Ethan Johnson",
                "avatar": "img/user/avatar/img-41.jpg",
                "date": "June 10, 2023",
                "rating": 4.7,
                "comment": "RoofMaster installed a new roof for my house, and it looks great. The roofers were professional, skilled, and completed the job on time. Highly satisfied!",
                "email": "ethan.johnson@example.com",
            },
            {
                "reviewer": "Mia Anderson",
                "avatar": "img/user/avatar/img-42.jpg",
                "date": "June 8, 2023",
                "rating": 4.3,
                "comment": "The roofing services provided by RoofMaster were satisfactory. The roofers were efficient, but there were a few minor issues that needed fixing afterward.",
                "email": "mia.anderson@example.com",
            },
        ],
    },
    {
        "company": "HomeSafe",
        "serviceType": "Home Security Systems",
        "location": "Port Harcourt, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦200 - ₦1,000,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "HomeSafe specializes in providing advanced home security systems to protect your property. Our state-of-the-art technology and expert installation ensure peace of mind for homeowners.",
        "reviews": [
            {
                "reviewer": "Benjamin Brown",
                "avatar": "img/user/avatar/img-43.jpg",
                "date": "June 11, 2023",
                "rating": 4.9,
                "comment": "I highly recommend HomeSafe for home security systems. They installed a comprehensive security system in my house, and I feel much safer now. The service was impeccable.",
                "email": "benjamin.brown@example.com",
            },
            {
                "reviewer": "Olivia Wilson",
                "avatar": "img/user/avatar/img-44.jpg",
                "date": "June 9, 2023",
                "rating": 4.7,
                "comment": "HomeSafe provided excellent customer service and installed a reliable security system in my home. The technicians were professional and addressed all my concerns.",
                "email": "olivia.wilson@example.com",
            },
        ],
    },
    {
        "company": "FloorCraft",
        "serviceType": "Flooring Services",
        "location": "Ibadan, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦300 - ₦600,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "FloorCraft offers high-quality flooring services for residential and commercial properties. Our skilled craftsmen install various flooring materials, including hardwood, tiles, and carpets.",
        "reviews": [
            {
                "reviewer": "David Wilson",
                "avatar": "img/user/avatar/img-45.jpg",
                "date": "June 12, 2023",
                "rating": 4.5,
                "comment": "FloorCraft installed new hardwood flooring in my living room, and it looks stunning. The craftsmanship was excellent, and the installers were professional and efficient.",
                "email": "david.wilson@example.com",
            },
            {
                "reviewer": "Emma Johnson",
                "avatar": "img/user/avatar/img-46.jpg",
                "date": "June 10, 2023",
                "rating": 4.2,
                "comment": "I had a satisfactory experience with FloorCraft. The flooring installation was good overall, but there were a few minor imperfections. Still, I'm happy with the result.",
                "email": "emma.johnson@example.com",
            },
        ],
    },
    {
        "company": "GardenGurus",
        "serviceType": "Gardening Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦150 - ₦400,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "GardenGurus provides professional gardening services to transform your outdoor space. Our skilled gardeners handle landscaping, maintenance, and plant care with precision and creativity.",
        "reviews": [
            {
                "reviewer": "Noah Thompson",
                "avatar": "img/user/avatar/img-47.jpg",
                "date": "June 13, 2023",
                "rating": 4.6,
                "comment": "I hired GardenGurus for landscaping my backyard, and they did an excellent job. The gardeners were knowledgeable, courteous, and delivered a beautiful garden. Highly recommended!",
                "email": "noah.thompson@example.com",
            },
            {
                "reviewer": "Sophie Anderson",
                "avatar": "img/user/avatar/img-48.jpg",
                "date": "June 11, 2023",
                "rating": 4.3,
                "comment": "GardenGurus provided satisfactory gardening services for my front yard. The gardeners were professional and completed the work as discussed. Good service overall.",
                "email": "sophie.anderson@example.com",
            },
        ],
    },
    {
        "company": "ApplianceExperts",
        "serviceType": "Appliance Repair Services",
        "location": "Abuja, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦200 - ₦500,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "ApplianceExperts specializes in repairing a wide range of home appliances, including refrigerators, washing machines, and air conditioners. Our technicians provide reliable and efficient repair services.",
        "reviews": [
            {
                "reviewer": "Daniel Wilson",
                "avatar": "img/user/avatar/img-49.jpg",
                "date": "June 14, 2023",
                "rating": 4.8,
                "comment": "ApplianceExperts repaired my malfunctioning refrigerator, and it's working perfectly now. The technician was prompt, knowledgeable, and fixed the issue efficiently.",
                "email": "daniel.wilson@example.com",
            },
            {
                "reviewer": "Ava Davis",
                "avatar": "img/user/avatar/img-50.jpg",
                "date": "June 12, 2023",
                "rating": 4.5,
                "comment": "I had a positive experience with ApplianceExperts. The technician diagnosed and repaired my washing machine quickly. The service was reliable and reasonably priced.",
                "email": "ava.davis@example.com",
            },
        ],
    },
    {
        "company": "SparkleClean",
        "serviceType": "House Cleaning Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦200 - ₦700,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "SparkleClean offers comprehensive house cleaning services to ensure your home is spotless and tidy. Our professional cleaners use eco-friendly products and efficient techniques to deliver exceptional results.",
        "reviews": [
            {
                "reviewer": "Olivia Wilson",
                "avatar": "img/user/avatar/img-51.jpg",
                "date": "June 15, 2023",
                "rating": 4.9,
                "comment": "I hired SparkleClean for a deep cleaning service, and they exceeded my expectations. The cleaners were thorough, punctual, and left my house sparkling clean.",
                "email": "olivia.wilson@example.com",
            },
            {
                "reviewer": "Ethan Brown",
                "avatar": "img/user/avatar/img-52.jpg",
                "date": "June 14, 2023",
                "rating": 4.7,
                "comment": "SparkleClean provided excellent house cleaning services. The cleaners paid attention to detail and left my home fresh and organized. Highly recommended!",
                "email": "ethan.brown@example.com",
            },
        ],
    },
    {
        "company": "TechFix",
        "serviceType": "Electronics Repair Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦250 - ₦600,000 /hour",
        "availabilityTime": "10am-7pm",
        "aboutCompany": "TechFix specializes in repairing electronic devices, including smartphones, laptops, and gaming consoles. Our skilled technicians ensure quick and reliable repairs to get your devices back in working condition.",
        "reviews": [
            {
                "reviewer": "Isabella Smith",
                "avatar": "img/user/avatar/img-53.jpg",
                "date": "June 16, 2023",
                "rating": 4.6,
                "comment": "TechFix repaired my smartphone screen, and the service was excellent. The technician was knowledgeable and completed the repair quickly.",
                "email": "isabella.smith@example.com",
            },
            {
                "reviewer": "William Johnson",
                "avatar": "img/user/avatar/img-54.jpg",
                "date": "June 15, 2023",
                "rating": 4.4,
                "comment": "I had a positive experience with TechFix. They repaired my laptop efficiently, and the pricing was reasonable. I would choose them for future repairs.",
                "email": "william.johnson@example.com",
            },
        ],
    },
    {
        "company": "HandyPlumbers",
        "serviceType": "Plumbing Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦300 - ₦500,000 /hour",
        "availabilityTime": "8am-6pm",
        "aboutCompany": "HandyPlumbers provides a wide range of plumbing services, including pipe repairs, drain cleaning, and bathroom installations. Our licensed plumbers ensure efficient and reliable solutions for all your plumbing needs.",
        "reviews": [
            {
                "reviewer": "Sophia Taylor",
                "avatar": "img/user/avatar/img-55.jpg",
                "date": "June 17, 2023",
                "rating": 4.8,
                "comment": "HandyPlumbers fixed a leaking pipe in my kitchen. The plumber arrived on time, identified the issue quickly, and repaired it effectively. I'm satisfied with the service.",
                "email": "sophia.taylor@example.com",
            },
            {
                "reviewer": "James Martinez",
                "avatar": "img/user/avatar/img-56.jpg",
                "date": "June 16, 2023",
                "rating": 4.5,
                "comment": "I had a great experience with HandyPlumbers. They installed a new toilet in my bathroom, and the plumber was skilled and professional. Highly recommended.",
                "email": "james.martinez@example.com",
            },
        ],
    },
    {
        "company": "FixItNow",
        "serviceType": "Handyman Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
        "hourlyRate": "₦150 - ₦800,000 /hour",
        "availabilityTime": "9am-5pm",
        "aboutCompany": "FixItNow offers comprehensive handyman services for home and office repairs. Our skilled handymen can handle various tasks, including painting, furniture assembly, and minor electrical work.",
        "reviews": [
            {
                "reviewer": "Emily Anderson",
                "avatar": "img/user/avatar/img-57.jpg",
                "date": "June 18, 2023",
                "rating": 4.7,
                "comment": "I hired FixItNow for some minor repairs in my home, and they did an excellent job. The handyman was skilled and completed the tasks efficiently. I'm satisfied with their service.",
                "email": "emily.anderson@example.com",
            },
            {
                "reviewer": "Joseph Rodriguez",
                "avatar": "img/user/avatar/img-58.jpg",
                "date": "June 17, 2023",
                "rating": 4.3,
                "comment": "FixItNow provided reliable and prompt service. The handyman fixed a broken cabinet in my office, and the outcome was satisfactory. I would recommend their services.",
                "email": "joseph.rodriguez@example.com",
            },
        ],
    },
    {
        "company": "EcoGardeners",
        "serviceType": "Gardening Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦200 - ₦900,000 /hour",
        "availabilityTime": "8am-6pm",
        "aboutCompany": "EcoGardeners specializes in providing professional gardening services. Our skilled gardeners create beautiful landscapes, offer lawn maintenance, and provide expert advice for plant care.",
        "reviews": [
            {
                "reviewer": "Daniel Clark",
                "avatar": "img/user/avatar/img-59.jpg",
                "date": "June 19, 2023",
                "rating": 4.9,
                "comment": "I hired EcoGardeners for landscaping services, and I'm extremely pleased with the results. The gardeners were skilled, creative, and transformed my outdoor space beautifully.",
                "email": "daniel.clark@example.com",
            },
            {
                "reviewer": "Samantha Hill",
                "avatar": "img/user/avatar/img-60.jpg",
                "date": "June 18, 2023",
                "rating": 4.6,
                "comment": "EcoGardeners provided excellent lawn maintenance services. The gardeners were attentive to detail and ensured my garden looked pristine. I highly recommend them.",
                "email": "samantha.hill@example.com",
            },
        ],
    },
    {
        "company": "CoolPro AC Services",
        "serviceType": "Air Conditioning Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦300 - ₦750,000 /hour",
        "availabilityTime": "10am-7pm",
        "aboutCompany": "CoolPro AC Services offers professional air conditioning services, including installation, repair, and maintenance. Our skilled technicians ensure optimal cooling performance for your comfort.",
        "reviews": [
            {
                "reviewer": "Ava Turner",
                "avatar": "img/user/avatar/img-61.jpg",
                "date": "June 20, 2023",
                "rating": 4.7,
                "comment": "CoolPro AC Services installed a new air conditioning unit in my home, and the technicians did a fantastic job. They were knowledgeable and completed the installation efficiently.",
                "email": "ava.turner@example.com",
            },
            {
                "reviewer": "Michael Cooper",
                "avatar": "img/user/avatar/img-62.jpg",
                "date": "June 19, 2023",
                "rating": 4.4,
                "comment": "I had a positive experience with CoolPro AC Services. They repaired my malfunctioning air conditioner promptly, and it's working perfectly now.",
                "email": "michael.cooper@example.com",
            },
        ],
    },
    {
        "company": "EliteElectricians",
        "serviceType": "Electrical Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
        "hourlyRate": "₦350 - ₦400,000 /hour",
        "availabilityTime": "8am-7pm",
        "aboutCompany": "EliteElectricians offers reliable electrical services for residential and commercial properties. Our licensed electricians handle installations, repairs, and safety inspections with precision.",
        "reviews": [
            {
                "reviewer": "Charlotte Hill",
                "avatar": "img/user/avatar/img-63.jpg",
                "date": "June 21, 2023",
                "rating": 4.8,
                "comment": "I'm impressed with the service provided by EliteElectricians. They fixed a faulty electrical outlet in my home promptly and professionally. Highly recommended.",
                "email": "charlotte.hill@example.com",
            },
            {
                "reviewer": "David Turner",
                "avatar": "img/user/avatar/img-64.jpg",
                "date": "June 20, 2023",
                "rating": 4.5,
                "comment": "EliteElectricians installed new lighting fixtures in my office, and the electricians did an excellent job. They were skilled, efficient, and delivered quality work.",
                "email": "david.turner@example.com",
            },
        ],
    },
    {
        "company": "SmartTech",
        "serviceType": "Smart Home Installation",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦400 - ₦900,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "SmartTech specializes in smart home installation services. Our technicians integrate various devices to enhance security, convenience, and energy efficiency in your home.",
        "reviews": [
            {
                "reviewer": "Grace Martin",
                "avatar": "img/user/avatar/img-65.jpg",
                "date": "June 22, 2023",
                "rating": 4.9,
                "comment": "I'm extremely satisfied with the smart home installation provided by SmartTech. The technicians were knowledgeable, and they configured the system to my preferences.",
                "email": "grace.martin@example.com",
            },
            {
                "reviewer": "Joseph Reed",
                "avatar": "img/user/avatar/img-66.jpg",
                "date": "June 21, 2023",
                "rating": 4.7,
                "comment": "SmartTech transformed my home into a smart and connected space. The installation process was smooth, and the technicians provided helpful explanations.",
                "email": "joseph.reed@example.com",
            },
        ],
    },
    {
        "company": "FixItRoof",
        "serviceType": "Roofing Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦500 - ₦700,000 /hour",
        "availabilityTime": "8am-5pm",
        "aboutCompany": "FixItRoof specializes in roofing services, including repairs, installations, and maintenance. Our experienced roofers ensure durable and reliable solutions for your property.",
        "reviews": [
            {
                "reviewer": "Oliver Mitchell",
                "avatar": "img/user/avatar/img-67.jpg",
                "date": "June 23, 2023",
                "rating": 4.8,
                "comment": "FixItRoof repaired a leaking roof in my house, and the roofers did an excellent job. They were skilled, efficient, and completed the repair to my satisfaction.",
                "email": "oliver.mitchell@example.com",
            },
            {
                "reviewer": "Natalie Wright",
                "avatar": "img/user/avatar/img-68.jpg",
                "date": "June 22, 2023",
                "rating": 4.5,
                "comment": "I'm happy with the roofing services provided by FixItRoof. The roofers were professional, and they completed the installation on time and within budget.",
                "email": "natalie.wright@example.com",
            },
        ],
    },
    {
        "company": "ProExterminators",
        "serviceType": "Pest Control Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday",
        "hourlyRate": "₦200 - ₦600,000 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "ProExterminators offers effective pest control services to eliminate pests from your home or business. Our trained exterminators use safe and eco-friendly methods for pest removal.",
        "reviews": [
            {
                "reviewer": "Henry Walker",
                "avatar": "img/user/avatar/img-69.jpg",
                "date": "June 24, 2023",
                "rating": 4.7,
                "comment": "ProExterminators provided efficient pest control services. The exterminator arrived on time, identified the issue, and effectively eliminated the pests.",
                "email": "henry.walker@example.com",
            },
            {
                "reviewer": "Ella Adams",
                "avatar": "img/user/avatar/img-70.jpg",
                "date": "June 23, 2023",
                "rating": 4.3,
                "comment": "I had a positive experience with ProExterminators. They treated my home for termites, and the results have been satisfactory. I appreciate their professionalism.",
                "email": "ella.adams@example.com",
            },
        ],
    },
    {
        "company": "CleanSweep",
        "serviceType": "Professional Cleaning Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦300 - ₦800,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "CleanSweep offers top-notch professional cleaning services for residential and commercial spaces. Our skilled cleaners ensure a spotless and hygienic environment.",
        "reviews": [
            {
                "reviewer": "Sophia Thompson",
                "avatar": "img/user/avatar/img-71.jpg",
                "date": "June 25, 2023",
                "rating": 4.9,
                "comment": "I'm impressed with the cleaning services provided by CleanSweep. The cleaners were thorough and paid attention to detail. I highly recommend their services.",
                "email": "sophia.thompson@example.com",
            },
            {
                "reviewer": "James Anderson",
                "avatar": "img/user/avatar/img-72.jpg",
                "date": "June 24, 2023",
                "rating": 4.7,
                "comment": "CleanSweep did an excellent job cleaning my office space. The cleaners were professional, and they completed the task efficiently.",
                "email": "james.anderson@example.com",
            },
        ],
    },
    {
        "company": "GardenGurus",
        "serviceType": "Landscaping and Gardening Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦400 - ₦900,000 /hour",
        "availabilityTime": "8am-5pm",
        "aboutCompany": "GardenGurus specializes in landscaping and gardening services. Our experienced team creates beautiful outdoor spaces tailored to your preferences.",
        "reviews": [
            {
                "reviewer": "Olivia Rodriguez",
                "avatar": "img/user/avatar/img-73.jpg",
                "date": "June 26, 2023",
                "rating": 4.8,
                "comment": "GardenGurus transformed my garden into a stunning oasis. The team was knowledgeable and worked diligently to bring my vision to life.",
                "email": "olivia.rodriguez@example.com",
            },
            {
                "reviewer": "Daniel Young",
                "avatar": "img/user/avatar/img-74.jpg",
                "date": "June 25, 2023",
                "rating": 4.6,
                "comment": "I'm satisfied with the landscaping services provided by GardenGurus. The team was creative, and they incorporated unique design elements in my garden.",
                "email": "daniel.young1@example.com",
            },
        ],
    },
    {
        "company": "QuickFix",
        "serviceType": "Handyman Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦200 - ₦600,000 /hour",
        "availabilityTime": "9am-7pm",
        "aboutCompany": "QuickFix offers reliable and efficient handyman services for various repair and maintenance tasks. Our skilled handymen ensure high-quality workmanship.",
        "reviews": [
            {
                "reviewer": "Emily Campbell",
                "avatar": "img/user/avatar/img-75.jpg",
                "date": "June 27, 2023",
                "rating": 4.7,
                "comment": "I had a great experience with QuickFix. The handyman fixed multiple issues in my home, and the results were excellent. I would hire them again.",
                "email": "emily.campbell@example.com",
            },
            {
                "reviewer": "Henry Ward",
                "avatar": "img/user/avatar/img-76.jpg",
                "date": "June 26, 2023",
                "rating": 4.5,
                "comment": "QuickFix provided prompt and efficient handyman services. The handyman was skilled and completed the tasks to my satisfaction.",
                "email": "henry.ward@example.com",
            },
        ],
    },
    {
        "company": "SparkleMaid",
        "serviceType": "Residential Cleaning Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦250 - ₦700,000 /hour",
        "availabilityTime": "8am-6pm",
        "aboutCompany": "SparkleMaid offers top-quality residential cleaning services to keep your home sparkling clean. Our dedicated cleaners ensure a thorough cleaning experience.",
        "reviews": [
            {
                "reviewer": "Emma Allen",
                "avatar": "img/user/avatar/img-77.jpg",
                "date": "June 28, 2023",
                "rating": 4.9,
                "comment": "SparkleMaid exceeded my expectations with their residential cleaning services. The cleaners were professional and paid attention to every detail.",
                "email": "emma.allen@example.com",
            },
            {
                "reviewer": "Samuel Foster",
                "avatar": "img/user/avatar/img-78.jpg",
                "date": "June 27, 2023",
                "rating": 4.6,
                "comment": "I'm satisfied with the residential cleaning services provided by SparkleMaid. The cleaners were punctual and thorough in their work.",
                "email": "samuel.foster@example.com",
            },
        ],
    },
    {
        "company": "FixItAll",
        "serviceType": "General Repair Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦150 - ₦500,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "FixItAll offers comprehensive general repair services for residential and commercial properties. Our skilled technicians handle various repair tasks.",
        "reviews": [
            {
                "reviewer": "Isabella Wood",
                "avatar": "img/user/avatar/img-79.jpg",
                "date": "June 29, 2023",
                "rating": 4.7,
                "comment": "FixItAll provided excellent general repair services. The technician was knowledgeable and resolved the issue efficiently.",
                "email": "isabella.wood@example.com",
            },
            {
                "reviewer": "Nathan Hill",
                "avatar": "img/user/avatar/img-80.jpg",
                "date": "June 28, 2023",
                "rating": 4.4,
                "comment": "I'm pleased with the general repair services provided by FixItAll. The technician was professional and completed the repair to my satisfaction.",
                "email": "nathan.hill@example.com",
            },
        ],
    },
    {
        "company": "TechAssist",
        "serviceType": "IT Support Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Tuesday, Wednesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦400 - ₦900,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "TechAssist offers reliable IT support services for businesses. Our experienced technicians ensure smooth functioning of your IT systems.",
        "reviews": [
            {
                "reviewer": "Aiden Brooks",
                "avatar": "img/user/avatar/img-81.jpg",
                "date": "June 30, 2023",
                "rating": 4.9,
                "comment": "TechAssist provided efficient IT support services for my business. The technician resolved the issues promptly, and I'm satisfied with their service.",
                "email": "aiden.brooks@example.com",
            },
            {
                "reviewer": "Chloe Collins",
                "avatar": "img/user/avatar/img-82.jpg",
                "date": "June 29, 2023",
                "rating": 4.6,
                "comment": "I'm impressed with the IT support services provided by TechAssist. The technician was knowledgeable and resolved the technical issues effectively.",
                "email": "chloe.collins@example.com",
            },
        ],
    },
    {
        "company": "PestControlPro",
        "serviceType": "Pest Control Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦300 - ₦800,000 /hour",
        "availabilityTime": "8am-7pm",
        "aboutCompany": "PestControlPro offers effective pest control services to protect your home or business from pests. Our experienced exterminators ensure a pest-free environment.",
        "reviews": [
            {
                "reviewer": "Mia Ward",
                "avatar": "img/user/avatar/img-83.jpg",
                "date": "July 1, 2023",
                "rating": 4.7,
                "comment": "PestControlPro provided reliable pest control services. The exterminator was thorough and addressed all pest-related concerns.",
                "email": "mia.ward@example.com",
            },
            {
                "reviewer": "Benjamin Cooper",
                "avatar": "img/user/avatar/img-84.jpg",
                "date": "June 30, 2023",
                "rating": 4.5,
                "comment": "I'm satisfied with the pest control services provided by PestControlPro. The exterminator was professional and ensured a pest-free environment.",
                "email": "benjamin.cooper@example.com",
            },
        ],
    },
    {
        "company": "PaintMaster",
        "serviceType": "Professional Painting Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦200 - ₦600,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "PaintMaster offers high-quality professional painting services for residential and commercial properties. Our skilled painters deliver exceptional results.",
        "reviews": [
            {
                "reviewer": "Ava Watson",
                "avatar": "img/user/avatar/img-85.jpg",
                "date": "July 2, 2023",
                "rating": 4.9,
                "comment": "PaintMaster did an outstanding job with the painting services. The painters were skilled and paid attention to detail. Highly recommended.",
                "email": "ava.watson@example.com",
            },
            {
                "reviewer": "David Allen",
                "avatar": "img/user/avatar/img-86.jpg",
                "date": "July 1, 2023",
                "rating": 4.7,
                "comment": "I'm pleased with the painting services provided by PaintMaster. The painters were professional and completed the job within the estimated time.",
                "email": "david.allen@example.com",
            },
        ],
    },
    {
        "company": "FixMyPlumbing",
        "serviceType": "Plumbing Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦250 - ₦700,000 /hour",
        "availabilityTime": "8am-5pm",
        "aboutCompany": "FixMyPlumbing offers reliable plumbing services for residential and commercial properties. Our expert plumbers handle various plumbing issues.",
        "reviews": [
            {
                "reviewer": "Oliver Turner",
                "avatar": "img/user/avatar/img-87.jpg",
                "date": "July 3, 2023",
                "rating": 4.8,
                "comment": "FixMyPlumbing provided efficient plumbing services. The plumber resolved the issue promptly, and I'm satisfied with their service.",
                "email": "oliver.turner@example.com",
            },
            {
                "reviewer": "Ella Walker",
                "avatar": "img/user/avatar/img-88.jpg",
                "date": "July 2, 2023",
                "rating": 4.6,
                "comment": "I'm impressed with the plumbing services provided by FixMyPlumbing. The plumber was skilled and ensured the plumbing system worked perfectly.",
                "email": "ella.walker@example.com",
            },
        ],
    },
    {
        "company": "RoofingExperts",
        "serviceType": "Roofing Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Wednesday, Thursday, Friday",
        "hourlyRate": "₦150 - ₦500,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "RoofingExperts specializes in providing high-quality roofing services for residential and commercial properties. Our experienced roofers ensure durable and well-crafted roofs.",
        "reviews": [
            {
                "reviewer": "Grace Baker",
                "avatar": "img/user/avatar/img-89.jpg",
                "date": "July 4, 2023",
                "rating": 4.7,
                "comment": "RoofingExperts did an excellent job with my roof installation. The roofers were skilled and completed the work within the agreed timeline.",
                "email": "grace.baker@example.com",
            },
            {
                "reviewer": "Liam Turner",
                "avatar": "img/user/avatar/img-90.jpg",
                "date": "July 3, 2023",
                "rating": 4.4,
                "comment": "I'm satisfied with the roofing services provided by RoofingExperts. The roofers were professional and ensured a sturdy roof.",
                "email": "liam.turner@example.com",
            },
        ],
    },
    {
        "company": "ElectroFix",
        "serviceType": "Electrical Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦400 - ₦900,000 /hour",
        "availabilityTime": "8am-7pm",
        "aboutCompany": "ElectroFix offers comprehensive electrical services for residential and commercial properties. Our skilled electricians handle various electrical tasks.",
        "reviews": [
            {
                "reviewer": "Lucy Wright",
                "avatar": "img/user/avatar/img-91.jpg",
                "date": "July 5, 2023",
                "rating": 4.7,
                "comment": "ElectroFix provided efficient electrical services. The electrician was knowledgeable and resolved the electrical issues effectively.",
                "email": "lucy.wright@example.com",
            },
            {
                "reviewer": "Maxwell Hall",
                "avatar": "img/user/avatar/img-92.jpg",
                "date": "July 4, 2023",
                "rating": 4.5,
                "comment": "I'm pleased with the electrical services provided by ElectroFix. The electrician was professional and ensured the safety of my electrical systems.",
                "email": "maxwell.hall@example.com",
            },
        ],
    },
    {
        "company": "SecureHome",
        "serviceType": "Home Security Services",
        "location": "Lagos, Nigeria",
        "daysAvailable": "Monday, Tuesday, Thursday, Friday, Saturday",
        "hourlyRate": "₦300 - ₦800,000 /hour",
        "availabilityTime": "9am-6pm",
        "aboutCompany": "SecureHome offers reliable home security services to protect your property. Our expert technicians ensure top-notch security systems.",
        "reviews": [
            {
                "reviewer": "Lily Harris",
                "avatar": "img/user/avatar/img-93.jpg",
                "date": "July 6, 2023",
                "rating": 4.8,
                "comment": "SecureHome provided excellent home security services. The technicians were knowledgeable and installed a comprehensive security system.",
                "email": "lily.harris@example.com",
            },
            {
                "reviewer": "Owen Adams",
                "avatar": "img/user/avatar/img-94.jpg",
                "date": "July 5, 2023",
                "rating": 4.6,
                "comment": "I'm satisfied with the home security services provided by SecureHome. The technicians were professional and ensured my property's safety.",
                "email": "owen.adams@example.com",
            },
        ],
    },
]


def generate_password(length=8):
    """Generate a random password with the specified length."""
    characters = string.ascii_letters + string.digits + string.punctuation
    password = "".join(random.choice(characters) for _ in range(length))
    return password


def generate_time_fields(availability_time):
    start_time_str, end_time_str = availability_time.split("-")
    start_time = datetime.strptime(start_time_str, "%I%p").time()
    end_time = datetime.strptime(end_time_str, "%I%p").time()

    # Assuming you want to store the times in UTC timezone
    start_time = timezone.make_aware(
        datetime.combine(timezone.now().date(), start_time)
    )
    end_time = timezone.make_aware(datetime.combine(timezone.now().date(), end_time))
    return start_time, end_time


print(len(search_results))
