nigerian_names = [
    "Abdullahi",
    "Adebowale",
    "Adeleke",
    "Adewale",
    "Adisa",
    "Ajayi",
    "Akintola",
    "Aliyu",
    "Amadi",
    "Amina",
    "Ani",
    "Babatunde",
    "Balogun",
    "Bello",
    "Chibuzo",
    "Chidinma",
    "Chika",
    "Chinwe",
    "Chukwuemeka",
    "Daniel",
    "Ebere",
    "Emeka",
    "Ezekiel",
    "Folake",
    "Funmilayo",
    "Ibe",
    "Ibrahim",
    "Ifeoma",
    "Isa",
    "Ishola",
    "Jelani",
    "Kalu",
    "Kemi",
    "Lola",
    "Mohammed",
    "Ngozi",
    "Nnamdi",
    "Nwachukwu",
    "Ojo",
    "Okoro",
    "Oladele",
    "Olaide",
    "Olalekan",
    "Olufemi",
    "Olumide",
    "Oluwaseun",
    "Oluwaseyi",
    "Onyeka",
    "Rasheed",
    "Sadiq",
]

# users = []
# for i in range(100):
#     name = random.choice(nigerian_names) + " " + random.choice(nigerian_names)
#     email = name.split(" ")[0].lower() + "." + str(i + 1) + "@example.com"
#     user = {"name": name, "email": email}
#     users.append(user)

users_list = [
    {"email": "bello.1@example.com", "name": "Bello Babatunde"},
    {"email": "ngozi.2@example.com", "name": "Ngozi Daniel"},
    {"email": "chika.3@example.com", "name": "Chika Emeka"},
    {"email": "folake.4@example.com", "name": "Folake Lola"},
    {"email": "amina.5@example.com", "name": "Amina Kalu"},
    {"email": "chika.6@example.com", "name": "Chika Ifeoma"},
    {"email": "olaide.7@example.com", "name": "Olaide Olufemi"},
    {"email": "kemi.8@example.com", "name": "Kemi Oluwaseyi"},
    {"email": "olufemi.9@example.com", "name": "Olufemi Lola"},
    {"email": "babatunde.10@example.com", "name": "Babatunde Adisa"},
    {"email": "kemi.11@example.com", "name": "Kemi Ebere"},
    {"email": "olalekan.12@example.com", "name": "Olalekan Aliyu"},
    {"email": "rasheed.13@example.com", "name": "Rasheed Ishola"},
    {"email": "ibe.14@example.com", "name": "Ibe Onyeka"},
    {"email": "chukwuemeka.15@example.com", "name": "Chukwuemeka Chika"},
    {"email": "kalu.16@example.com", "name": "Kalu Adewale"},
    {"email": "chinwe.17@example.com", "name": "Chinwe Lola"},
    {"email": "nwachukwu.18@example.com", "name": "Nwachukwu Olalekan"},
    {"email": "adewale.19@example.com", "name": "Adewale Bello"},
    {"email": "aliyu.20@example.com", "name": "Aliyu Olalekan"},
    {"email": "chinwe.21@example.com", "name": "Chinwe Chinwe"},
    {"email": "ani.22@example.com", "name": "Ani Ishola"},
    {"email": "ani.23@example.com", "name": "Ani Olalekan"},
    {"email": "chukwuemeka.24@example.com", "name": "Chukwuemeka Daniel"},
    {"email": "chukwuemeka.25@example.com", "name": "Chukwuemeka Abdullahi"},
    {"email": "lola.26@example.com", "name": "Lola Aliyu"},
    {"email": "nwachukwu.27@example.com", "name": "Nwachukwu Olufemi"},
    {"email": "mohammed.28@example.com", "name": "Mohammed Akintola"},
    {"email": "oluwaseyi.29@example.com", "name": "Oluwaseyi Rasheed"},
    {"email": "nnamdi.30@example.com", "name": "Nnamdi Ani"},
    {"email": "akintola.31@example.com", "name": "Akintola Akintola"},
    {"email": "ezekiel.32@example.com", "name": "Ezekiel Ebere"},
    {"email": "amina.33@example.com", "name": "Amina Ani"},
    {"email": "kemi.34@example.com", "name": "Kemi Kemi"},
    {"email": "ifeoma.35@example.com", "name": "Ifeoma Chukwuemeka"},
    {"email": "olumide.36@example.com", "name": "Olumide Sadiq"},
    {"email": "ibrahim.37@example.com", "name": "Ibrahim Olaide"},
    {"email": "chidinma.38@example.com", "name": "Chidinma Adisa"},
    {"email": "ojo.39@example.com", "name": "Ojo Adeleke"},
    {"email": "ibrahim.40@example.com", "name": "Ibrahim Olalekan"},
    {"email": "babatunde.41@example.com", "name": "Babatunde Balogun"},
    {"email": "olumide.42@example.com", "name": "Olumide Ani"},
    {"email": "okoro.43@example.com", "name": "Okoro Ibe"},
    {"email": "emeka.44@example.com", "name": "Emeka Ezekiel"},
    {"email": "adisa.45@example.com", "name": "Adisa Oluwaseun"},
    {"email": "emeka.46@example.com", "name": "Emeka Sadiq"},
    {"email": "kemi.47@example.com", "name": "Kemi Chidinma"},
    {"email": "chukwuemeka.48@example.com", "name": "Chukwuemeka Adebowale"},
    {"email": "folake.49@example.com", "name": "Folake Adewale"},
    {"email": "onyeka.50@example.com", "name": "Onyeka Rasheed"},
    {"email": "ani.51@example.com", "name": "Ani Chibuzo"},
    {"email": "kemi.52@example.com", "name": "Kemi Nnamdi"},
    {"email": "onyeka.53@example.com", "name": "Onyeka Abdullahi"},
    {"email": "kalu.54@example.com", "name": "Kalu Olumide"},
    {"email": "olalekan.55@example.com", "name": "Olalekan Onyeka"},
    {"email": "lola.56@example.com", "name": "Lola Chinwe"},
    {"email": "nwachukwu.57@example.com", "name": "Nwachukwu Ibe"},
    {"email": "oladele.58@example.com", "name": "Oladele Chidinma"},
    {"email": "ezekiel.59@example.com", "name": "Ezekiel Sadiq"},
    {"email": "kemi.60@example.com", "name": "Kemi Ajayi"},
    {"email": "chinwe.61@example.com", "name": "Chinwe Isa"},
    {"email": "kalu.62@example.com", "name": "Kalu Daniel"},
    {"email": "isa.63@example.com", "name": "Isa Emeka"},
    {"email": "aliyu.64@example.com", "name": "Aliyu Olalekan"},
    {"email": "adebowale.65@example.com", "name": "Adebowale Chidinma"},
    {"email": "ezekiel.66@example.com", "name": "Ezekiel Aliyu"},
    {"email": "abdullahi.67@example.com", "name": "Abdullahi Ojo"},
    {"email": "kemi.68@example.com", "name": "Kemi Daniel"},
    {"email": "ishola.69@example.com", "name": "Ishola Amina"},
    {"email": "oluwaseyi.70@example.com", "name": "Oluwaseyi Chibuzo"},
    {"email": "oluwaseyi.71@example.com", "name": "Oluwaseyi Abdullahi"},
    {"email": "ebere.72@example.com", "name": "Ebere Adisa"},
    {"email": "chukwuemeka.73@example.com", "name": "Chukwuemeka Akintola"},
    {"email": "funmilayo.74@example.com", "name": "Funmilayo Balogun"},
    {"email": "ebere.75@example.com", "name": "Ebere Nnamdi"},
    {"email": "ojo.76@example.com", "name": "Ojo Mohammed"},
    {"email": "adisa.77@example.com", "name": "Adisa Sadiq"},
    {"email": "olumide.78@example.com", "name": "Olumide Mohammed"},
    {"email": "onyeka.79@example.com", "name": "Onyeka Babatunde"},
    {"email": "chika.80@example.com", "name": "Chika Ibe"},
    {"email": "sadiq.81@example.com", "name": "Sadiq Adisa"},
    {"email": "olalekan.82@example.com", "name": "Olalekan Adebowale"},
    {"email": "chibuzo.83@example.com", "name": "Chibuzo Chinwe"},
    {"email": "chukwuemeka.84@example.com", "name": "Chukwuemeka Chukwuemeka"},
    {"email": "adeleke.85@example.com", "name": "Adeleke Chukwuemeka"},
    {"email": "daniel.86@example.com", "name": "Daniel Kalu"},
    {"email": "ifeoma.87@example.com", "name": "Ifeoma Ani"},
    {"email": "amina.88@example.com", "name": "Amina Balogun"},
    {"email": "ngozi.89@example.com", "name": "Ngozi Amadi"},
    {"email": "oluwaseyi.90@example.com", "name": "Oluwaseyi Balogun"},
    {"email": "ani.91@example.com", "name": "Ani Oluwaseyi"},
    {"email": "bello.92@example.com", "name": "Bello Olaide"},
    {"email": "okoro.93@example.com", "name": "Okoro Chibuzo"},
    {"email": "amina.94@example.com", "name": "Amina Nnamdi"},
    {"email": "ajayi.95@example.com", "name": "Ajayi Funmilayo"},
    {"email": "ajayi.96@example.com", "name": "Ajayi Ishola"},
    {"email": "akintola.97@example.com", "name": "Akintola Folake"},
    {"email": "chika.98@example.com", "name": "Chika Akintola"},
    {"email": "nwachukwu.99@example.com", "name": "Nwachukwu Isa"},
    {"email": "chika.100@example.com", "name": "Chika Adeleke"},
]
